{% set name = "pivy" %}
{% set version = "0.6.6dev" %}
{% set sha256 = "16f2e339e5c59a6438266abe491013a20f53267e596850efad1559564a2c1719" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}.tar.gz
    git_url: https://github.com/FreeCAD/pivy
    git_tag: master

build:
    number: 0
    skip:
        true  # [py < 38]

requirements:
    build:
        - {{ compiler("cxx") }}
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - msinttypes  # [win]
        - cmake
        - swig
    host:
        - python
        - coin3d
        - soqt
        - qt
        - colorama  # [not win]   
    run:
        - python
        - coin3d
        - qt
        - pyside2
        - soqt

test:
    imports:
        - pivy.coin
        - pivy.gui.soqt

about:
    home: https://github.com/FreeCAD/pivy
    license: ISC
    license_file: LICENSE
    summary: python bindings to coin3d.
    doc_url: https://github.com/FreeCAD/pivy
    dev_url: https://github.com/FreeCAD/pivy

extra:
    recipe-maintainers:
        - looooo
